apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobo.fullname" . }}-kpi
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
  {{- if .Values.kpi.serviceAnnotations }}
  annotations:
  {{- include "common.tplvalues.render" ( dict "value" .Values.kpi.serviceAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.kpi.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 8001 
      targetPort: 8000
    - name: nginx
      protocol: TCP
      port: {{ .Values.kpi.service.port }}
      targetPort: 80
  selector:
    {{- include "kobo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kpi
